urls.py
from django.urls import path, include

from . import views

app_name = 'mainsite'
urlpatterns = [
    # path('blog/', include('blog.urls')),
    path('', views.indexpage, name='index'),
    path('blog/', views.BlogListView.as_view(), name='bloglist'),
    path('blog/post', views.PostBlog.as_view(), name='blogpost'),
    path('blog/upload', views.UpImage.as_view(), name='uploader'),
    path('blog/<slug:slug>/edit', views.EditBlog.as_view(), name='blogedit'),
    path('blog/<slug:slug>', views.Blog.as_view(), name='blog'),
    path('projects/<slug:slug>', views.ProjectPage.as_view(), name='project'),
    path('<str:page>', views.sitepage),
]

models.py
from django.db import models
from django.urls import reverse
from django.core.files.storage import FileSystemStorage

# I may change how this works as it doesn't necessarily need to be an entire db entry
# maybe change it to something like a wp_options model with 'setting name' and 'setting value'
# another option is to just use settings.py 
class SiteSettings(models.Model):
    site_title=models.CharField(max_length=255)
    site_slogan=models.CharField(max_length=255)
    

class SitePage(models.Model):
    page_name=models.CharField(max_length=20)
    title=models.CharField(max_length=255, blank=True)
    body=models.TextField(blank=True)

    def __str__(self):
        return self.page_name


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True, db_index=True)
    # tags marked hidden will not show up on unauthenticated user-facing  website interface
    # hidden = models.BooleanField()
    def __str__(self):
        return self.name


class PostImage(models.Model):
    name = models.CharField(max_length=100)
    photo = models.ImageField(upload_to='images/')

        
class BlogPost(models.Model):
    post_date=models.DateTimeField()
    slug=models.SlugField(unique=True)
    title=models.CharField(max_length=255)
    blurb=models.CharField(max_length=255, blank=True)
    author=models.CharField(max_length=100)
    body=models.TextField()
    is_published=models.BooleanField()
    tags=models.ManyToManyField(Tag)
    # modifield fields ?
    def get_absolute_url(self):
        return reverse('mainsite:blog', args=[self.slug])

class Project(models.Model):
    slug=models.SlugField(unique=True)
    name=models.CharField(max_length=100)
    short_description=models.CharField(max_length=255, blank=True)
    description=models.TextField()
    source_url=models.URLField(blank=True)
    language=models.ManyToManyField(Tag, blank=True)
    # project_logo ?

views.py
import markdown2

from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.utils import timezone
from django.urls import reverse, reverse_lazy
from django import forms

from .models import SitePage
from .models import BlogPost
from .models import Project
from .models import SiteSettings
from .models import PostImage


def sitepage(request, page='index'):
    data = get_object_or_404(SitePage, page_name=page)
    pagebody = markdown2.markdown(data.body)
    context = {
            "page" : data,
            "site_title" : page,
            "page_body": pagebody,
            }
    return render(request, 'mainsite/sitepage.html', context=context)


def indexpage(request):
    data = get_object_or_404(SitePage, page_name='index')
    pagebody = markdown2.markdown(data.body, extras=['fenced-code-blocks'])
    context = {
            "page" : data,
            "site_title" : data.title,
            "page_body": pagebody,
            "projects": Project.objects.all(),
            # TODO I feel like hardcoding this tag here is a bad idea.. maybe I'll do it with template filters instead
            "recent_blogs": BlogPost.objects.filter(post_date__lte=timezone.now(), is_published=True, tags__name="programming").order_by('-post_date')[:5]
            }
    return render(request, 'mainsite/indexpage.html', context=context)

class BlogListView(generic.ListView):
    model = BlogPost
    context_object_name = "blog_list"
    def get_queryset(self):
        if self.request.user.is_authenticated:
            queryset = BlogPost.objects.order_by('-post_date')
        else:
            queryset = BlogPost.objects.filter(post_date__lte=timezone.now(), is_published=True).order_by('-post_date')
        return queryset


class Blog(generic.DetailView):
    model = BlogPost
    context_object_name = "post"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'].body = markdown2.markdown(context['post'].body)
        # do the markdown stuff here
        return context


# this is a silly hack that shouldn't even be here
class BlogForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = '__all__'
        # render a manytomany as a textfield so that I can enter tags as a comma delimited list.
        # requires custom form validation/saving due to that of course
        # might need a custom widget to display the names instead of IDs...
        # or just override the data itself to be a list
#        widgets = {
#                'tags': forms.CharField.widget
#                }


class PostBlog(LoginRequiredMixin, generic.CreateView):
    login_url = '/' #TODO this needs to be changed
    form_class = BlogForm
    model = BlogPost

class EditBlog(LoginRequiredMixin, generic.UpdateView):
    login_url = '/' #TODO this needs to be changed
    model = BlogPost
    form_class = BlogForm

class ProjectPage(generic.DetailView):
    model = Project
    context_object_name = "project"


class UpImage(LoginRequiredMixin, generic.CreateView):
    login_url = "/"
    model = PostImage
    fields = '__all__'
    success_url='/media/{photo}'

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
	<head>
		<title>{% block titletag %}{{ site_title }}{% endblock %}</title>
		<link rel="stylesheet" type="text/css" href="{% static "mainsite/main.css" %}">
	</head>
	<body>
		<div id="topbar">
			<span id="logo"><a href='/'>Useful|idiom</a></span>
			<span id="top-menu">
				<span class="menu-item"><a href="{% url 'mainsite:bloglist' %}">Blog</a></span> 
				<span class="menu-item"><a href="#">Projects</a></span><span class='caret'><span> 
				<span class="menu-item"><a href="{% url 'mainsite:index' %}">About</a></span>
				<ul id='projectmenu-popup'>
				{% for prjn, prjl in project_links.items %}
				<li><a href="{{ prjl }}">{{ prjn }}</a></li>
				{% endfor %}
				</ul>
			</span>
		</div>
		<div id="columnlayout">
		{# block mainbody #}
		
		{% block mainpanel %}example content{% endblock %}
		{% block rightbar %}
		{% endblock %}
		</div>
		<div id="footer">
                    Useful Idiom. Other footer stuff.
		</div>
	
	</body>
</html>

templates/mainsite/blogpost_detail.html
{% extends 'base.html' %}

{% block titletag %}{{ site_title }} - {{post.title}}{% endblock %}
{% block mainpanel %}
<div id='leftcontentarea'>
	TODO: This template needs changes and CSS
	{% if user.is_authenticated %}<a href='{% url 'mainsite:blogedit' post.slug %}'>edit</a>{% endif %}
	{% if not post.is_published %}<div id='drafnotice'> THIS IS A DRAFT POST THAT IS NOT PUBLISHED </div>{% endif %}
	<h1>{{ post.title }}</h1>

	<span id='byline'>By <span id='blogauthor'>{{ post.author }}</span> on {{ post.post_date|date }}</br></span>
	{# post.tags.all|join:" - " #}


	<p>{{ post.body|safe }}<p>
</div>

{% endblock %}

templates/mainsite/blogpost_form.html
{% extends 'base.html' %}
{% block mainpanel %}
<div id='leftcontentarea'>
	TODO: This template needs to manually build the form, CSS, and probably some js<br>
	<form method=post>
	{% csrf_token %}
	<table>
	{{ form.as_table }}
        </table>
        <input type='submit'>

	</form>
	Markdown Preview:<div id='markdownpriview'></div>

</div>

{% endblock %}

templates/mainsite/blogpost_list.html
{% extends "base.html" %}

{% block mainpanel %}
<div id="leftcontentarea">
	<div> {% if user.is_authenticated %} <a href='{% url 'mainsite:blogpost' %}'>New post</a>{% endif %}</div>
	<ul>
	{% for blog in blog_list %} 
	<li>[{{ blog.post_date|date }}] <a href='{% url 'mainsite:blog' blog.slug %}'>{{ blog.title }}</a>
		{% if not blog.is_published %} [DRAFT] {% endif %}
		<br> 
	{{ blog.blurb }}</li>
	{% endfor %}


	</ul></div>
{% endblock %}

templates/mainsite/indexpage.html
{% extends "base.html" %}

{% block mainpanel %}
<div id="leftcontentarea">
Hi {{ user }}
{{ page_body|safe }}


<h3> Projects: </h3>
{% for proj in projects %}
<a href='{% url 'mainsite:project' proj.slug %}'>{{ proj.name }}</a> - {{ proj.short_description }}
{% endfor %}

<h3> Recent Developmet Blog Posts: </h3>
{% for post in recent_blogs %}
<a href='{% url 'mainsite:blog' post.slug %}'>{{post.title}}</a><br> 
<blockquote>   {{post.blurb}}</blockquote>
{% endfor %}

</div>
{% endblock %}

templates/mainsite/postimage_form.html
{% extends 'base.html' %} 
{% block mainpanel %}
        <form method="post" enctype="multipart/form-data"> 
	  {% csrf_token %} 
	  {{ form.as_p }} 
	  <button type="submit">Upload</button>
	</form>
	{% endblock %}

templates/mainsite/project_detail.html
{% extends 'base.html' %}

{% block titletag %}{{ site_title }} - {{project.name}}{% endblock %}
{% block mainpanel %}
<div id="leftcontentarea">
	TODO: This template needs a bunch of work and CSS
	<h1>{{ project.name }}</h1>
	<span id='byline'>{{ project.short_description }}</span>
        <br>

	<div>
		<br>
	Tags:{{ project.language.all }}<br>
        Source: {{ project.source_url }}<br>
        </div>
	<p>{{ project.description }}</p>

	Blog posts about {{ project.name }}

</div>

{% endblock %}

templates/mainsite/sitepage.html
{% extends "base.html" %}

{% block mainpanel %}
<div id="leftcontentarea">
<span><h1>{{ page.title }}</h1></span>
{{ page_body|safe }}
{{ user }}
</div>
{% endblock %}